apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-app
  description: Python app that displays time test
  annotations:
    github.com/project-slug: rishabhsvats/platform-engineering
    backstage.io/techdocs-ref: dir:./python-app
    backstage.io/source-location: url:https://github.com/rishabhsvats/platform-engineering
spec:
  type: service
  owner: user:default/test1
  lifecycle: experimental
